### ISSUE TITLE
Add arrows to note, to separate text location and noted location

### ISSUE THREAD

**Issue by ben-edna** [jgeudens/ModbusScope#117]
When adding a note, it not is completely clear what point in the graph is pointed at by the note.
Adding an arrow would solve this. Also notes can be moved. and multiple notes can be placed around a same location noting other behaviors.

Below mocked screenshot is ugly, but hopefully clear 😄 

![modbusscope_bands](https://user-images.githubusercontent.com/37540691/64760049-08dc0580-d539-11e9-982e-82d84709aa6b.png)

**Comment by jgeudens** [comment]
Please check https://github.com/spoorcc/ModbusScope/commit/f7470bb9c2596fd85956d89964adec3d1502edaa#r35084291. This should be fixed.

For the rest, the changes look good.
