### ISSUE TITLE
Add support for 32-bit registers

### ISSUE THREAD

**Issue by ben-edna** [jgeudens/ModbusScope#129]
It would be useful to make 32-bit register values possible in ModbusScope.

**Comment by jgeudens** [comment]
This feature can be broken down into 2 features: Support for 32 bit registers and parsing 32-bit setting from a mbc file.

Parsing the 32 bit endiannes setting from mbc is moved to feature (#130).

This feature will include:

- [ ] Add 32 bit option to register definitions and reading them correctly.
- [ ] Add setting for 32 bit endiannes in mbs file

**Comment by jgeudens** [comment]
Implemented in 50f52f387d34741fd7382d7cb9c9172cf6fbe10d
