### ISSUE TITLE
Time wraps on very long logs

### ISSUE THREAD

**Issue by de-sach** [jgeudens/ModbusScope#139]
When sampling a register for some time, the times shown on the graph wrap.
So you get for example 6:00:00 - 12:00:00 - 18:00:00 - 0:00:00.
I assume that, since the time counts from 0:00:00 onward, the time should be 6:00:00 - 12:00:00 - 18:00:00 - 24:00:00.

**Comment by jgeudens** [comment]
Indeed, you are correct. I will investigate and improve.

**Comment by jgeudens** [comment]
Fixed and tested with current master
