### ISSUE TITLE
Highlight invalid token in expression editor

### ISSUE THREAD

**Issue by ben-edna** [jgeudens/ModbusScope#142]
When an invalid token is present in the expression, Modbusscope knows the position as can be seen below.

![afbeelding](https://user-images.githubusercontent.com/37540691/98341615-653c9700-200f-11eb-96bc-9960fa7b3b4e.png)

It would be nice for the user to instead of counting tokens, get a visual help by highlighting the unexpected token red.

**Comment by jgeudens** [comment]
Implemented in https://github.com/jgeudens/ModbusScope/pull/197
