### ISSUE TITLE
Make it possible to show wall clock time in x-scale

### ISSUE THREAD

**Issue by ben-edna** [jgeudens/ModbusScope#147]
When doing a test and trying to cross-reference a issue with another log, it would be easy if the wall clock time is shown.

**Comment by jgeudens** [comment]
Do you mean absolute time?

https://modbusscope.readthedocs.io/en/latest/pages/configuration.html#configure-log-settings

**Comment by spoorcc** [comment]
Yes indeed, but then in the graph

**Comment by jgeudens** [comment]
I'm not sure what you mean. When absolute times is enabled, the log shows absolute time and date, but also the graph.

![Screenshot from 2021-01-29 20-23-38](https://user-images.githubusercontent.com/9089936/106318266-f5d1ee80-626f-11eb-955c-7dda8218389e.png)

**Comment by spoorcc** [comment]
Ouch, didn't knew that, please consider this closed. I can make a certain customer happy 😁
