### ISSUE TITLE
Change some configuration checkboxes with radio buttons with choices

### ISSUE THREAD

**Issue by jgeudens** [jgeudens/ModbusScope#148]
For some options, the meaning and implications aren't clear from the current UI: For example #147.

The end user would be better informed with a radio button that indicates the difference between the choices. More information can then be added in the documentation.

**Comment by spoorcc** [comment]
For the example in #147 maybe the location "log settings" was confusing. I would expect this option in the x-axis settings below the graph. I think I've associated "log settings" with the exported log and not with the graph.

**Comment by jgeudens** [comment]
Good point. Maybe some more UI changes can make things clearer and more user friendly.

**Comment by jgeudens** [comment]
Mostly done in #160
