### ISSUE TITLE
Enconding issue in MBCFileImporter

### ISSUE THREAD

**Issue by ben-edna** [jgeudens/ModbusScope#151]
I have a mbc file with the following entry:

```xml
<?xml version="1.0" encoding="utf-8"?>
...
    <var><reg>40001</reg><text>Estimated System Flow [m³/h]</text><decimals>3</decimals><type>uint32</type><rw>r</rw><bcol>255,225,255</bcol></var>
```

In ModbusControl this is shown correct:
![afbeelding](https://user-images.githubusercontent.com/37540691/109994416-943cee00-7d0d-11eb-90ec-1da6d09ca16b.png)

But in ModbusScope, I think something goes wrong with the encoding:

![afbeelding](https://user-images.githubusercontent.com/37540691/109994499-a9198180-7d0d-11eb-8a73-a7aae0619dfa.png)

My guess is that since the mbc is read as plain text file in [`ImportMbcDialog::updateMbcRegisters()`]( https://github.com/jgeudens/ModbusScope/blob/8b05404fa868fa8dac9e56b4ce51efb165249aa1/src/dialogs/importmbcdialog.cpp#L138-L139) and the content is passed as a string no encoding detection is done by QDomDocument.

**Comment by jgeudens** [comment]
Thank you the report. I will check it out.

**Comment by jgeudens** [comment]
Hmm, I can't seem to reproduce the issue on Windows (or Ubuntu). Are you using the latest release (v3.1.0)?

![afbeelding](https://user-images.githubusercontent.com/9089936/110169052-65e80d00-7df8-11eb-8575-91ffc7a26ed6.png)

**Comment by ben-edna** [comment]
On windows with this version: 
![afbeelding](https://user-images.githubusercontent.com/37540691/110201274-851b8480-7e62-11eb-93ce-2de8bacb9f95.png)

Attached a minimal reproducing file with the error:
[repro.zip](https://github.com/jgeudens/ModbusScope/files/6095071/repro.zip)


(Sidenote: I also noticed when the `<rw>` tag is missing only an "invalid" message is given, not that it it missing a field.)

**Comment by ben-edna** [comment]
I also upgraded to v3.1.0 and issue is still present

**Comment by spoorcc** [comment]
I no longer see this in v3.7.0:

![image](https://user-images.githubusercontent.com/1345842/219592843-e5d30f63-1f25-48aa-996e-a5ae2ae310a4.png)

**Comment by jgeudens** [comment]
Thanks for testing again.
