### ISSUE TITLE
Add link(s) to online resources

### ISSUE THREAD

**Issue by ben-edna** [jgeudens/ModbusScope#152]
Currently there is a great set of documentation 😄  at [readthedocs](https://modbusscope.readthedocs.io/).
It is reachable through "?"> "About" > "Homepage" button.

Maybe make it easier to find:
- Add a separate entry in the `? ` menu with "Online help" or  "Documentation"
- Let the "Homepage" button link to github?
- Add a link to "Issues" so people can report more easily.

**Comment by jgeudens** [comment]
Great suggestions. I have put them on my todo list to improve UX.
