### ISSUE TITLE
Feature: Let text filter also work on register number

### ISSUE THREAD

**Issue by ben-edna** [jgeudens/ModbusScope#174]
When importing registers from an MBC file, you can use the text filter.
If you know the modbusregister, it would be easy that when you type the register number in the filter field, that the registers with that number (or part of) are shown as well.

**Comment by jgeudens** [comment]
Good idea

**Comment by spoorcc** [comment]
Quick service :smile:

**Comment by jgeudens** [comment]
Sometimes you can ask for something on the exact moment that I have time and "goesting" to implement something useful.

Well done :grin:
