### ISSUE TITLE
Feature Request: Allow full 16-bit addressing of Holding Registers

### ISSUE THREAD

**Issue by SweJake** [jgeudens/ModbusScope#181]
Hi,

I was very happy when i stumbled upon this project!
Just what I was looking for to read/log my new HeatPump.
But...
The interesting Modbus Holding Registers of my manufacturer all start above standard.
Please see:
https://ctc.se/file-download/a9fcdab53f94cdb3ae70beb27e9372b7.pdf
(Ex. "Outdoor temp." = Holding Reg# 62147)
![image](https://user-images.githubusercontent.com/97973689/149986861-9b566bca-b4b5-4e1b-8e2b-6f19eca9c293.png)
(I've tried to tweak the settingsfile, *.mbs, to enter higher value but can see in WireShark that it doesn't work)
I would so much like to have this working with my HeatPump.
So..

**Feature Request:**
Add a checkbox stating: "Allow out of range Holding Registers" or similar ?

**Comment by jgeudens** [comment]
I'm glad that ModbusScope might be useful for you.

I'm currently working on making ModbusScope more generic, separating Modbus registers from a data graph using expressions and such. Your feature request will be useful to support more devices in the field which don't adhere very strictly to the standard.

I think it should be doable. I hope to take some time this week for an initial implementation.

**Comment by jgeudens** [comment]
I have added a test to read a large register address. During the refactoring I mentioned, I already removed some obsolete checks on the register address. Apparently, I already support registers 40001 to 65353 in the current beta version. You can download this beta from my CI build artifacts (https://ci.appveyor.com/project/jgeudens/modbusscope/builds/42262445/artifacts).

You can use following expression to read register 61500 with the new syntax.

![image](https://user-images.githubusercontent.com/9089936/150219213-ce398eb2-47b6-41c0-8cf3-e5160a34386f.png)

Of course, this isn't the complete range since 40001 is just an offset for holding registers that isn't used in the protocol itself so the full range is 40001 to 105536. but allowing this would require some more changes.

I hope you can use ModbusScope with your device with this build. I would appreciate some feedback whether it worked or not.

Good night.

**Comment by jgeudens** [comment]
Support for the full 16-bit range is merged through #185

**Comment by spoorcc** [comment]
Hi @SweJake,

If I'm not mistaken the 40001 offset is always subtracted in a read holding register message (function code 3).  See also http://www.simplymodbus.ca/FC03.htm.

The packets contents seems correct to me.

**Comment by SweJake** [comment]
Oh, I think we misunderstood each other, and that's mostly my fault for being unclear.

In the document:
https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf
at chapter: "4.3 MODBUS Data model"
They are talking about the "normal" 4-block device, which I believe this program supports excellently!
...but later on they also describe the 1-block device. (mine)

So, if i want to read ANY register i have to send a read request ,0x03 "Read holding reg." preferably, followed by the full 16-bit reg-address:
![image](https://user-images.githubusercontent.com/97973689/151018365-00559831-e2a7-4e31-ae56-c1ddb5f07b40.png)

And i will get the "OutDoor Temp." (and divide it by 10 --> 1.5℃)
![image](https://user-images.githubusercontent.com/97973689/151019195-0b6c1d7f-b362-4dfc-af12-c0dfd64b7f37.png)

See the document of my manufacturer in the original request.

So maybe the title of the request would have been: "Please add support for 1-block ModBus devices"?

**Comment by jgeudens** [comment]
Today I learned that modbus has a 1-block model.

As long as the data is available through the read holding register function code (FC3). You should be able to use ModbusScope. With this [PR](https://github.com/jgeudens/ModbusScope/pull/185), I have added full support for the 16-bit adressing. You can download the latest build [from the CI](https://ci.appveyor.com/project/jgeudens/modbusscope/builds/42292945/artifacts).

I must admit I don't really understand the register addressing of your device, so I can't help you there. But you should be able to use ModbusScope to read all data. ModbusScope will substract the 40001 offset automatically from the address. But you can work around this by adding 40001 to the requested address.

* `${40001}` will give you raw address 0 in the Wireshark packet.
* `${102148}` will give you raw address 62147 in the packet.

I hope this information is useful for you.

**Comment by SweJake** [comment]
Somewhat awkward to enter the reg-addresses, but i can live with that.
I'm completely satisfied!
This supports my setup of a: CTC-EcoAir408 and CTC-EcoLogic S.
I will give it a thoroughly "Burn-In Test"
![image](https://user-images.githubusercontent.com/97973689/151339417-b3bdbbad-516b-4a72-847a-eb64827b318c.png)

Big Thanks !
