### ISSUE TITLE
Axis scaling gets reset when pressing start

### ISSUE THREAD

**Issue by pluyckx** [jgeudens/ModbusScope#210]
### Description
When you have changed the axis scaling using the UI and you press start, the scaling is set back to `auto`.

### Steps to Reproduce
1. Change x and/or y scaling from auto to another option using the UI
2. Start logging
3. The scaling is set to auto again

### Expected Behavior
The scaling does not reset. The start button only starts logging.
To reset the scaling, there is `File` -> `Reload Project`.

**Comment by jgeudens** [comment]
I agree that when sliding window is active, it shouldn't switch to auto. But I think it is a different case when manual is active. The graph is cleared when starting a new log. When manual is selected, the 0 s time might not be visible at the moment, so the new data won't be visible, so resetting to auto seems to be the best way here.
