### ISSUE TITLE
How do you use Modbus Scope to draw IEEE754 double and float types

### ISSUE THREAD

**Issue by whyily** [jgeudens/ModbusScope#226]
How do you use Modbus Scope to draw IEEE754 double and float types, for example No, I don't know how to use the compose Expression for double and float types，thanks!

**Comment by jgeudens** [comment]
At the moment, float and double types aren't supported out of the box.

You can parse the different components (sign, exponent and mantissa) from a 32-bit or 64-bit integer that has been read with registers. But as I'm not really familiar with IEEE754, I'm not sure if you can construct the correct float with further expressions.
