### ISSUE TITLE
Crash when importing data from MBC

### ISSUE THREAD

**Issue by jgeudens** [jgeudens/ModbusScope#229]
1) Log some data
2) Stop log
3) Import register from MBC
4) Crash

Reported by @ben-edna 

I have been able to reproduce the issue.

Technical details: When adding a register, the temporary data file is updated. But sometimes, the data file is already updated when the graph doesn't have valid data yet. So crash...

**Comment by spoorcc** [comment]
Nice, good to hear you've found it 👍
