### ISSUE TITLE
Time representation in graph

### ISSUE THREAD

**Issue by pluyckx** [jgeudens/ModbusScope#31]
Wouldn't it be nice to represent the time as hh:mm:ss on the x-axis instead of autoscaling point numbers? It's a bit more readable :).

**Comment by pluyckx** [comment]
I've made a patch:
https://gist.githubusercontent.com/pluyckx/51ebfa6fbc5001bf3553/raw/b8876d67e9ea4560f51db66cd13fdc53889ae3a7/0001-Merge-commit-403b9f9-from-GraphViewer.patch

**Comment by jgeudens** [comment]
Sorry, I did the change myself because patch didn't apply cleanly. (And functionality is split into new function to add another feature).
