### ISSUE TITLE
Read registers from different servers

### ISSUE THREAD

**Issue by lsteynen** [jgeudens/ModbusScope#46]
Wouldn't it be nice that we can sample registers from different servers? I'd like to read some temperatures from one server and a temperature from another. I first thought of adding an IP field to each register but to be as flexible as possible you'd need to add IP address, port and slaveID to each register. That's a lot. It's also a lot to show in the legend window and in the csv file. It might be better to define a list of targets, each with a name, IP address, port and slaveID. Then, in the registers list, refer to a target name for each register.

**Comment by jgeudens** [comment]
Will be added in next release.
