### ISSUE TITLE
Move legend to the left?

### ISSUE THREAD

**Issue by lsteynen** [jgeudens/ModbusScope#49]
I often feel that the legend gets in the way of viewing recent data, because the legend is on the right and new data arrives on the right. I'd like to have a check item in the view menu to move the legend to the left. And make it configurable in the mbs file too please.

**Comment by jgeudens** [comment]
Partially added in 69d232a4dad366eb70bfe505a028c5b4a5b5e449 (0.7.4). Real release will be 1.0.0.

**Comment by jgeudens** [comment]
Suggestion from @lsteynen: Also include legend hidden option

**Comment by jgeudens** [comment]
Done: debc689d73127b4caea2876b358ac2e3c191ad4c and a335feabb10cc26357904ffa3d55a80e5c95b9a6
