### ISSUE TITLE
Data Import not working

### ISSUE THREAD

**Issue by pluyckx** [jgeudens/ModbusScope#64]
When importing data, I get the following error:
Invalid data (while processing data)
Line: .........
Are you sure the decimal separator character is according to your locale?
Expected decimal separator: ';'

**Comment by jgeudens** [comment]
Can you send sample file? Email?

**Comment by jgeudens** [comment]
File is not needed anymore. The error message was wrong. It showed the data separator character instead of the decimal point character. The decimal point character according to the system locale is used.
