### ISSUE TITLE
Idea: how about an error log?

### ISSUE THREAD

**Issue by lsteynen** [jgeudens/ModbusScope#72]
Also concerning issues #70 and #71.
I also experienced some trouble to determine the cause of a problem. I suggest to add an error log window. You can simply add a new dialog form that has a (readonly) textbox that shows the error log. In case of an error you can add a line to it like:
_Connect to 192.168.0.1:502 failed (Connection refused)_
_Read: reg=40001, quant=10: ERROR: INVALID ADDRESS EXCEPTION (2)_

**Comment by jgeudens** [comment]
Implemented in 91c39547e8cacecc9e808b9284cf9d0d743ce528
