### ISSUE TITLE
The -opengl option is not recognized

### ISSUE THREAD

**Issue by lsteynen** [jgeudens/ModbusScope#93]
The -opengl option is not recognized. I get an error dialog "Unknown options: o, p, e, n, g, l. And Modbusscope does not start. Using ModbusScope v1.3.0 on Windows 7.

**Comment by jgeudens** [comment]
Please use "--opengl". (double dash)

[Info](http://serverfault.com/questions/387935/whats-the-difference-betwen-the-single-dash-and-double-dash-flags-on-shell-comm)

**Comment by lsteynen** [comment]
Ah. Your v1.3.0 features list on https://github.com/jgeudens/ModbusScope/releases shows it with a single dash  :-)

**Comment by jgeudens** [comment]
Oops.

Fixed
