### ISSUE TITLE
Show value under cursor isn't disabled when application looses focus

### ISSUE THREAD

**Issue by jgeudens** [jgeudens/ModbusScope#98]
Show value under cursor isn't disabled when application looses focus.

**Comment by pluyckx** [comment]
A test case:
ModbusScope is on the foreground and the cursur is above the graph view. Then start an application using a shortcut that contains the Ctrl key (eg, launch launchy using Ctrl + Alt + Space). This will trigger the bug if you close launchy.

**Comment by jgeudens** [comment]
Fixed in 16d5ecc477e376426aaae9b1848a0748092b22fd
